name: gestion_finance
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cupertino_icons: ^1.0.5
  google_fonts: ^5.0.0
  sizer: ^2.0.15
  animated_bottom_navigation_bar: ^1.2.0
  percent_indicator: ^4.2.3
  icon_badge: ^1.0.0
  fl_chart: ^0.63.0
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  http: ^1.0.0
  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.0
#  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
