import 'package:flutter/material.dart';
const Color primary = Color(0xfff2f9fe);
const Color secondary = Color(0xFFdbe4f3);
const Color black = Color(0xFF000000);
const Color white = Color(0xFFFFFFFF);
const Color grey = Colors.grey;
const Color red = Color.fromARGB(253, 236, 8, 31);
const Color green = Color.fromARGB(255, 8, 177, 59);
const Color blue = Color(0xFF2Bc2ff);
const Color buttonColor = Color(0xff3e4784);
const Color mainFontColor = Color(0xff565c95);
const Color arrowbgColor = Color(0xffe4e9f7);
